export const TOKEN_RECEIVE = 'TOKEN_RECEIVE';
export const TOKEN_COOKIE_LOAD = 'TOKEN_COOKIE_LOAD';

export const USER_RECEIVE = 'USER_RECEIVE';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';

export const USER_BOOKMARK = 'USER_BOOKMARK';
export const USER_BOOKMARK_SUCCESS = 'USER_BOOKMARK_SUCCESS';
