export const GOOGLE_DRIVE_OPEN_MODAL = 'GOOGLE_DRIVE_OPEN_MODAL';
export const GOOGLE_DRIVE_FILES_RECEIVED = 'GOOGLE_DRIVE_FILES_RECEIVED';

export const GOOGLE_DRIVE_LIST_FILES = 'GOOGLE_DRIVE_LIST_FILES';
export const GOOGLE_DRIVE_LIST_FILES_NAME = 'GOOGLE_DRIVE_LIST_FILES_NAME';
export const GOOGLE_DRIVE_LIST_FILES_LOADING = 'GOOGLE_DRIVE_LIST_FILES_LOADING';

export const GOOGLE_DRIVE_UPLOAD_FILE = 'GOOGLE_DRIVE_UPLOAD_FILE';
export const GOOGLE_DRIVE_UPLOAD_FILE_LOADING = 'GOOGLE_DRIVE_UPLOAD_FILE_LOADING';
