export const SEARCH_GO = 'SEARCH_GO';
export const SEARCH_IMPORT = 'SEARCH_IMPORT';
export const SEARCH_IMPORTED = 'SEARCH_IMPORTED';
export const SEARCH_RECEIVE = 'SEARCH_RECEIVE';
export const SEARCH_UPDATE_Q = 'SEARCH_UPDATE_Q';
