export const EDIT_PAPER_FETCH = 'EDIT_PAPER_FETCH';
export const EDIT_PAPER_RECEIVE = 'EDIT_PAPER_RECEIVE';
export const EDIT_PAPER_RESET = 'EDIT_PAPER_RESET';

export const EDIT_PAPER_UPDATE = 'EDIT_PAPER_UPDATE';

export const EDIT_PAPER_REQUIRE_DRIVE = 'EDIT_PAPER_REQUIRE_DRIVE';
export const EDIT_PAPER_LOGIN = 'EDIT_PAPER_LOGIN';

export const EDIT_PAPER_GOOGLE_DRIVE_HAS_ACCESS = 'EDIT_PAPER_GOOGLE_DRIVE_HAS_ACCESS';
