export const RECEIVE_ARXIV = 'RECEIVE_ARXIV';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const SEARCH_ARXIV = 'SEARCH_ARXIV';
export const UPDATE_ARXIV_OFFSET = 'UPDATE_ARXIV_OFFSET';
