export const PAPER_LIST_FETCH = 'PAPER_LIST_FETCH';
export const PAPER_LIST_RECEIVED = 'PAPER_LIST_RECEIVED';

export const PAPER_LIST_LOADING_START = 'PAPER_LIST_LOADING_START';
export const PAPER_LIST_LOADING_STOP = 'PAPER_LIST_LOADING_STOP';

export const PAPER_LIST_UPDATE_FILTERS = 'PAPER_LIST_UPDATE_FILTERS';
export const PAPER_LIST_UPDATE_PAGINATION = 'PAPER_LIST_UPDATE_PAGINATION';
