export const IMPORTS_FILE_LOADED = 'IMPORTS_FILE_LOADED';
export const IMPORTS_PAPERS_RECEIVED = 'IMPORTS_PAPERS_RECEIVED';

export const IMPORTS_IMPORT_START = 'IMPORTS_IMPORT_START';
export const IMPORTS_IMPORT_DONE = 'IMPORTS_IMPORT_DONE';
